language: python
python:
  - "2.7"
virtualenv:
  system_site_packages: true
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y gnupg2 secure-delete haveged python-dev python-pip sqlite python-distutils-extra python-poppler xvfb firefox
install:
  - pip install --upgrade distribute
  - pip install -r securedrop/source-requirements.txt
  - pip install -r securedrop/document-requirements.txt
  - pip install -r securedrop/test-requirements.txt
  - ./setup_dev.sh -u
script:
  - python securedrop/tests/unit_tests.py
  - python securedrop/tests/functional/submit_and_retrieve_message.py
  - python securedrop/tests/functional/submit_and_retrieve_file.py
