language: python
python:
  - "2.7"
virtualenv:
  system_site_packages: true
install:
  - pip install --upgrade distribute
  - pip install -r source-requirements.txt
  - pip install -r document-requirements.txt
  - pip install -r test-requirements.txt
script:
  - ./setup_dev.sh -u
